general-settings:
  # The range of coherence for players to be considered nearby.
  min-distance: 10
  # Worlds where the plugin is disabled.
  disabled-worlds:
    - "lobby"
  # Do you want to enable debug logs? default: false
  dev-logs: false

# Message customization, Supports Minimessage.
message-formats:
  help-message: "<gradient:#5e4fa2:#f79459>Cohere Plugin Help</gradient>\n/cohere help - Shows this message."
  reload-message: "<green>Cohere plugin reloaded successfully.</green>"

coherences:
  xpshare:
    enabled: true
    # Type of sharing: 'add' or 'subtract'
    # 'add': Clones a percentage of the XP to nearby players without reducing the original amount.
    # 'subtract': Divides the XP evenly among nearby players.
    type: "add"
    # Percentage of XP to be shared with nearby players (only for 'add' type).
    # For example, 50 means 50% of the original XP is given to each nearby player.
    shared-percentage: 50
  potionshare:
    enabled: true
    # Levels to decrease when sharing potions.
    level-decrease: 1
